version: "3.7"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    networks:
      - ecommerce_internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce_bo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    image: crismed0101/ecommerce-backend:latest
    networks:
      - network_public
      - ecommerce_internal
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ecommerce_bo
      - APP_NAME=E-commerce Backend
      - APP_VERSION=1.0.0
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - SHOPIFY_WEBHOOK_SECRET=${SHOPIFY_WEBHOOK_SECRET}
      - ALLOWED_ORIGINS=https://ecom-app.bytebase.my
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ecommerce.rule=Host(`ecom-app.bytebase.my`)"
        - "traefik.http.routers.ecommerce.entrypoints=websecure"
        - "traefik.http.routers.ecommerce.priority=1"
        - "traefik.http.routers.ecommerce.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ecommerce.loadbalancer.server.port=8000"
        - "traefik.http.routers.ecommerce.service=ecommerce"
      resources:
        limits:
          cpus: "2"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    external: true
    name: ecommerce_postgres_data

networks:
  network_public:
    external: true
    name: network_public
  ecommerce_internal:
    driver: overlay
    name: ecommerce_internal
